name: Sheets Monitoring AI

on:
  schedule:
    # Запуск каждый день в 07:00 UTC (10:00 по МСК)
    - cron: '0 7 * * *'
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Обновили до v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install gspread google-auth requests openai

      - name: Run script
        env:
          G_JSON: ${{ secrets.G_JSON }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python main.py
